name: "Integration Tests"
on:
  push:


jobs:
  test-host:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: [ '7.3', '7.2']
        mysql-images: [ 'mysql:5.7', 'mysql:8']
    services:
      mysql:
        image: ${{ matrix.mysql-images }}
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      nginx:
        image: flyingmana/openmage-action-service:nginx
        ports:
          - 8080:80
        volumes:
          - ${{ github.workspace }}/:/var/www
#          - ${{ github.workspace }}/.github/workflows/integration/nginx.conf:/etc/nginx/conf.d/default.conf
      fpm:
        image: openmage/php:7.3.20
        ports:
          - 9000
        volumes:
          - ${{ github.workspace }}/:/var/www
#          - ${{ github.workspace }}/.github/workflows/fpm-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
    steps:
      - uses: actions/checkout@v2
      - name: Verify MySQL connection from host
        run: |
          sudo apt-get install -y mysql-client
          mysql --host 127.0.0.1 --port 3306 -uroot -ppassword -e "SHOW DATABASES"
          mysql --host 127.0.0.1 --port 3306 -uroot -ppassword -e "SHOW VARIABLES LIKE \"%version%\""
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-versions }}
          extension-csv: mbstring #optional, setup extensions
          ini-values-csv: post_max_size=256M, short_open_tag=On #optional, setup php.ini configuration
          coverage: none #optional, setup coverage driver
          pecl: true #optional, setup PECL
      - name: Check PHP Version
        run: php -v
      - name: curl test
        run: curl http://localhost:8080/README.md
