name: Release Building

on:
  release:
    types: [created]
#  push

jobs:
  distrubutable_composer_json:
#    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: "checkout repository"
      uses: actions/checkout@master
    - name: "install hub"
      run: "sudo snap install hub --classic"
    - name: chown 
      run: sudo chown root:root /
    - name: hub version
      run: hub version
    - name: hub help
      run: hub help
    - name: hub release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG: ${{ toJson(github.event.release.tag_name) }}
      run: hub release
    - name: attache composer.json to Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG: ${{ (github.event.release.tag_name) }}
#        TAG: "a8"
      run: hub release edit $TAG --attach composer.json --message="$TAG"
    - name: attache composer.lock to Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG: ${{ (github.event.release.tag_name) }}
      run: hub release edit $TAG --attach composer.lock --message="$TAG"
    
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
  debug:
    runs-on: ubuntu-latest
    
    steps:
    - name: Dump GitHub context (Tag Name)
      env:
        GITHUB_CONTEXT_TAG_NAME: ${{ toJson(github.event.release.tag_name) }}
      run: echo "$GITHUB_CONTEXT_TAG_NAME"
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"
  
