name: CI

on:
  project_column:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
  distrubutable_composer_json:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: attache Build to Release
      uses: elgohr/Github-Hub-Action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: release edit $({ github.ref }) --attach composer.json
    
